import "./globals.css";
import { Noto_Sans_Balinese } from "next/font/google";

const inter = Noto_Sans_Balinese({
  weight: "400", // or any other allowed value
  style: "normal", // or "italic" if needed
  subsets: ["latin"],
  // other properties as required
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-sans`}>{children}</body>
    </html>
  );
}
